import { Metadata } from "next";

import TopBrands from "@/components/TopBrands";
import NewBrands from "@/components/NewBrands";
import FilteredProviders from "@/components/providers/FilteredProviders";
import Providers from "@/components/providers/Providers";
import GuideSlotsPage from "@/components/GuideSlotsPage";


export const metadata: Metadata = {
  title: "Game Providers | New Brand",
  description: "Generated by create next app",
};

export default async function Casinos() {
  return (
    <div className="page-bonuses">
      <Providers />
      {/* <TopBrands /> */}
      <FilteredProviders />
      <GuideSlotsPage />
    </div>
  );
}
