import { Metadata } from "next";

import BrandSearchPage from "@/components/BrandSearchPage";
import SearchBrands from "@/components/SearchBrands";

export const metadata: Metadata = {
  title: "Search | New Brand",
  description: "Generated by create next app",
};

export default async function Search() {
    
  return (
    <div className="page-bonuses">
        <BrandSearchPage showBrands={[]} />
    </div>
  );
}
