import { Metadata } from "next";
import FilteredCountriesCasino from "@/components/country/FilteredCountriesCasino";
import GuideSlotsPage from "@/components/GuideSlotsPage";
import Newzealand from "@/components/country/Newzealand";

export const metadata: Metadata = {
  title: "New Zeakand Casinos | New Brand",
  description: "Generated by create next app",
};

export default async function Bonuses() {
  
  return (
    <div className="page-bonuses">
      <Newzealand />
      {/* <TopBrands /> */}
      <FilteredCountriesCasino />
      <GuideSlotsPage />
    </div>
  );
}
