import { Metadata } from "next";

import TopBrands from "@/components/TopBrands";
import NewBrands from "@/components/NewBrands";
import FilteredBonuses from "@/components/bonuses//FilteredBonuses";
import PreviewBonuses from "@/components/PreviewBonuses";
import GuideSlotsPage from "@/components/GuideSlotsPage";

export const metadata: Metadata = {
  title: "Bonuses | New Brand",
  description: "Generated by create next app",
};

export default async function Bonuses() {
  return (
    <div className="page-bonuses">
      <PreviewBonuses />
      <TopBrands />
      <FilteredBonuses />
      <GuideSlotsPage />
    </div>
  );
}
