import { Analytics } from "@vercel/analytics/react";
import { TheHeader } from "@/components/TheHeader";
import "./globals.css";
import type { Metadata } from "next";
import { TheFooter } from "@/components/TheFooter";
// import RandomWindow from "@/components/random/RandomWindow";


export const metadata: Metadata = {
  title: "This is a new brand",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body>
          {/* <RandomWindow /> */}
          <TheHeader />
          <main>
            {children}
            <Analytics />
          </main>
          <TheFooter />
        </body>
    </html>
  );
}
