
"use client";
import { TheHeader } from "@/components/TheHeader";
import "./globals.css";
import type { Metadata } from "next";
import { TheFooter } from "@/components/TheFooter";
import { I18nextProvider } from "react-i18next";
import i18n from "@/components/i18n"; // Шлях до вашого файлу i18n.js

export const metadata: Metadata = {
  title: "This is a new brand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
 
        <TheHeader />
        <I18nextProvider i18n={i18n}> {/* Додали обгортку I18nextProvider */}
        <main>{children}</main>
        </I18nextProvider>
        <TheFooter />
      </body>
    </html>
  );
}


// import { TheHeader } from "@/components/TheHeader";
// import { HeaderForSearch } from "@/components/HeaderForSearch";
// import "./globals.css";
// import type { Metadata } from "next";
// import { TheFooter } from "@/components/TheFooter";

// export const metadata: Metadata = {
//   title: "This is a new brand",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
//   context,
// }: {
//   children: React.ReactNode;
//   context: any;
// }) {
//   const isSearchPage = context.req.url === "/search"; // Используйте context.req.url
//   return (
//     <html lang="en">
//       <body>
//         {isSearchPage ? <HeaderForSearch /> : <TheHeader />}
//         <main>{children}</main>
//         <TheFooter />
//       </body>
//     </html>
//   );
// }
