import { Metadata } from "next";

import TopBrands from "@/components/TopBrands";
import NewBrands from "@/components/NewBrands";
import FilteredBonuses from "@/components/bonuses//FilteredBonuses";
import PreviewBonuses from "@/components/PreviewBonuses";
import GuideSlotsPage from "@/components/GuideSlotsPage";
import ExclusiveBonuses from "@/components/bonuses/ExclusiveBonuses";

export const metadata: Metadata = {
  title: "Exclusive  Bonuses | New Brand",
  description: "Generated by create next app",
};

export default async function Bonuses() {
  
  return (
    <div className="page-bonuses">
      <ExclusiveBonuses />
      {/* <TopBrands /> */}
      <FilteredBonuses />
      <GuideSlotsPage />
    </div>
  );
}
