import { Metadata } from "next";
import GuideSlotsGuide from "@/components/GuideSlotsGuide";

export const metadata: Metadata = {
  title: "Guides | New Brand",
  description: "Generated by create next app",
};



export default function Guides() {
 
  return (
    <>
      <div className="main__container">
        <h1 className="pt-12 pb-4">Guides page</h1>
        <p>
          If you aspire to hit the jackpot, delve into the world of online slots
          through our comprehensive guides on CasinoFreak.com. All the
          information you need, from paylines to progressive jackpots, is
          available on a single platform! Stay updated with the latest
          developments in the slot gambling realm and even try out free slot
          games directly from your device.
        </p>

       <GuideSlotsGuide />
      </div>
    </>
  );
}
