import { Metadata } from "next";

import TopBrands from "@/components/TopBrands";
import NewBrands from "@/components/NewBrands";
import FilteredCountriesCasino from "@/components/country/FilteredCountriesCasino";
import PreviewBonuses from "@/components/PreviewBonuses";
import GuideSlotsPage from "@/components/GuideSlotsPage";
import Australia from "@/components/country/Australia";

export const metadata: Metadata = {
  title: "Australian casino | New Brand",
  description: "Generated by create next app",
};

export default async function Bonuses() {
  
  return (
    <div className="page-bonuses">
      <Australia />
      {/* <TopBrands /> */}
      <FilteredCountriesCasino />

      <GuideSlotsPage />
    </div>
  );
}
