import { Metadata } from "next";

import TopBrands from "@/components/TopBrands";
import NewBrands from "@/components/NewBrands";
import FilteredCountriesCasino from "@/components/country/FilteredCountriesCasino";
import PreviewBonuses from "@/components/PreviewBonuses";
import GuideSlotsPage from "@/components/GuideSlotsPage";
import AllCasinos from "@/components/country/AllCasinos";

export const metadata: Metadata = {
  title: "All Casinos by Country | New Brand",
  description: "Generated by create next app",
};

export default async function Bonuses() {
  return (
    <div className="page-bonuses">
      <AllCasinos />
      {/* <TopBrands /> */}
      <FilteredCountriesCasino />
      <GuideSlotsPage />
    </div>
  );
}
