import { Metadata } from "next";

import TopBrands from "@/components/TopBrands";
import NewBrands from "@/components/NewBrands";
import FilteredProviders from "@/components/providers/FilteredProviders";
import GuideSlotsPage from "@/components/GuideSlotsPage";
import Amusnet from "@/components/providers/Amusnet";

export const metadata: Metadata = {
  title: "Amusnet | New Brand",
  description: "Generated by create next app",
};

export default async function Bonuses() {
  
  return (
    <div className="page-bonuses">
      <Amusnet />
      {/* <TopBrands /> */}
      <FilteredProviders />

      <GuideSlotsPage />
    </div>
  );
}
