import { Metadata } from "next";

import TopBrands from "@/components/TopBrands";
import NewBrands from "@/components/NewBrands";


export const metadata: Metadata = {
  title: "Free spins | New Brand",
  description: "Generated by create next app",
};

export default async function FreeSpins() {
  return (
    <>
      <div className="main__container">
        <h1>FreeSpins page</h1>
        <TopBrands />
         <NewBrands />
      </div>
    </>
  );
}
